kind: pipeline
name: build

steps:
  - name: build
    image: python:alpine
    commands:
      - pip wheel .
      - rm -r pds.egg-info/ build/
      - mkdir package
      - mv *.whl package
      - rm package/PyYAML-*
  - name: test
    image: python:alpine
    commands:
      - pip install package/*.whl
      - pds test
  - name: publish
    image: pwddocker/drone-publish:latest
    environment:
      PASS:
        from_secret: pass
      USER:
        from_secret: user
    commands:
      - python3 -m twine upload --repository-url https://git.glebmail.xyz/api/packages/PythonPrograms/pypi -u $USER -p $PASS package/*.whl
    when:
      event:
        - push
      branch:
        - master
  - name: publish-docker
    image: plugins/docker
    settings:
      username:
        from_secret: user-docker
      password:
        from_secret: pass-docker
      repo: pwddocker/pds
      tags: latest
    when:
      event:
        - push
      branch:
        - master