kind: pipeline
name: build
steps:
  - name: build
    image: python:alpine
    commands:
      - pip wheel .
      - rm -r pds.egg-info/ build/
      - mkdir package
      - mv *.whl package
  - name: test
    image: python
    commands:
      - pip install package/*.whl
      - pcsd test
  - name: publish
    image: pwddocker/drone-publish:latest
    environment:
      PASS:
        from_secret: pass
      USER:
        from_secret: user
    commands:
      - python3 -m twine upload --repository-url https://git.glebmail.xyz/api/packages/PythonPrograms/pypi -u $USER -p $PASS package/*.whl
    when:
      event:
        - push
        - tag
      branch:
        - master
